# This file was generated by GoReleaser. DO NOT EDIT.
class Mongocli < Formula
  desc "The MongoDB Command Line Interface (mongocli) is a tool for managing your MongoDB cloud services, like MongoDB Atlas, MongoDB Cloud Manager, and MongoDB Ops Manager."
  homepage "https://github.com/mongodb/mongocli"
  version "1.9.0"
  bottle :unneeded
  depends_on arch: :x86_64
  
  if OS.mac?
    url "https://github.com/mongodb/mongocli/releases/download/v1.9.0/mongocli_1.9.0_macos_x86_64.zip"
    sha256 "fb8fea2222e5d058d066af84858ba4e483c2c6280878d295e594471382ebd09c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mongodb/mongocli/releases/download/v1.9.0/mongocli_1.9.0_linux_x86_64.tar.gz"
    sha256 "bb745cd35cd96567e25db9eea6033512e67cc0a4e70fe54e88c73bc01cde4142"
  end

  def install
    bin.install "mongocli"
    (bash_completion/"mongocli.sh").write `#{bin}/mongocli completion bash`
    (zsh_completion/"_mongocli").write `#{bin}/mongocli completion zsh`
    (fish_completion/"mongocli.fish").write `#{bin}/mongocli completion fish`
  end

  test do
    system "#{bin}/mongocli --version"
  end
end
